use std::fs;

//An... Exhastive list of every single pokemon
use Type::*;
use num_enum::TryFromPrimitive;
use std::convert::TryFrom;
use LegendStatus::*;
use csv::{self, Reader};
use try_catch::catch;

//Pokemon to make extra cases for
//Alolan Raichu (make it possible from Pikachu)
//Unknown (make it randomize letter)
//Vivilion (make it change pattern)
//Flabebe line (make colors random)
//Minior (make colors random)
//Basculin (colors)
//Deerling and Sawsbuck randomize seasons

#[derive(Copy, Clone)]
#[derive(TryFromPrimitive)]
#[derive(PartialEq)]
#[repr(i32)]
pub enum Pokemon{
    Bulbasaur,
    Ivysaur,
    Venusaur,
    Venusaur_Mega,
    Charmander,
    Charmeleon,
    Charizard,
    Squirtle,
    Wartortle,
    Blastoise,
    Caterpie,
    Metapod,
    Butterfree,
    Weedle,
    Kakuna,
    Beedrill,
    Pidgey,
    Pidgeotto,
    Pidgeot,
    Rattata,
    Rattata_Alolan,
    Raticate,
    Raticate_Alolan,
    Spearow,
    Fearow,
    Ekans,
    Arbok,
    Pikachu,
    Raichu,
    Raichu_Alolan,
    Sandshrew,
    Sanshrew_Alolan,
    Sandslash,
    Sandslash_Alolan,
    Nidoran_F,
    Nidorina,
    Nidoqueen,
    Nidoran_M,
    Nidorino,
    Nidoking,
    Clefairy,
    Clefable,
    Vulpix,
    Vulpix_Alolan,
    Ninetales,
    Ninetales_Alolan,
    Jigglypuff,
    Wigglytuff,
    Zubat,
    Golbat,
    Oddish,
    Gloom,
    Vileplume,
    Paras,
    Parasect,
    Venonat,
    Venomoth,
    Diglett,
    Diglett_Alolan,
    Dugtrio,
    Dugtrio_Alolan,
    Meowth,
    Meowth_Alolan,
    Persian,
    Persian_Alolan,
    Psyduck,
    Golduck,
    Mankey,
    Primeape,
    Growlithe,
    Arcanine,
    Poliwag,
    Poliwhirl,
    Poliwrath,
    Abra,
    Kadabra,
    Alakazam,
    Machop,
    Machoke,
    Machamp,
    Bellsprout,
    Weepinbell,
    Victreebel,
    Tentacool,
    Tentacruel,
    Geodude,
    Geodude_Alolan,
    Graveler,
    Graveler_Alolan,
    Golem,
    Golem_Alolan,
    Ponyta,
    Rapidash,
    Slowpoke,
    Slowbro,
    Magnemite,
    Magneton,
    Farfetchd,
    Doduo,
    Dodrio,
    Seel,
    Dewgong,
    Grimer,
    Grimer_Alolan,
    Muk,
    Muk_Alolan,
    Shellder,
    Cloyster,
    Gastly,
    Haunter,
    Gengar,
    Onix,
    Drowzee,
    Hypno,
    Krabby,
    Kingler,
    Voltorb,
    Electrode,
    Exeggcute,
    Exeggutor,
    Exeggutor_Alolan,
    Cubone,
    Marowak,
    Marowak_Alolan,
    Hitmonlee,
    Hitmonchan,
    Lickitung,
    Koffing,
    Weezing,
    Rhyhorn,
    Rhydon,
    Chansey,
    Tangela,
    Kangaskhan,
    Horsea,
    Seadra,
    Goldeen,
    Seaking,
    Staryu,
    Starmie,
    Mr_Mime,
    Scyther,
    Jynx,
    Electabuzz,
    Magmar,
    Pinsir,
    Tauros,
    Magikarp,
    Gyarados,
    Lapras,
    Ditto,
    Eevee,
    Vaporeon,
    Jolteon,
    Flareon,
    Porygon,
    Omanyte,
    Omastar,
    Kabuto,
    Kabutops,
    Aerodactyl,
    Snorlax,
    Articuno,
    Zapdos,
    Moltres,
    Dratini,
    Dragonair,
    Dragonite,
    MewTwo,
    Mew,
    Chikorita,
    Bayleef,
    Meganium,
    Cyndaquil,
    Quilava,
    Typhlosion,
    Totodile,
    Croconaw,
    Feraligatr,
    Sentret,
    Furret,
    Hoothoot,
    Noctowl,
    Ledyba,
    Ledian,
    Spinarak,
    Ariados,
    Crobat,
    Chinchou,
    Lanturn,
    Pichu,
    Cleffa,
    Igglybuff,
    Togepi,
    Togetic,
    Natu,
    Xatu,
    Mareep,
    Flaaffy,
    Ampharos,
    Bellossom,
    Marill,
    Azumarill,
    Sudowoodo,
    Politoed,
    Hoppip,
    Skiploom,
    Jumpluff,
    Aipom,
    Sunkern,
    Sunflora,
    Yanma,
    Wooper,
    Quagsire,
    Espeon,
    Umbreon,
    Murkrow,
    Slowking,
    Misdreavus,
    Unown,
    Wobbuffet,
    Girafarig,
    Pineco,
    Forretress,
    Dunsparce,
    Gligar,
    Steelix,
    Snubbull,
    Granbull,
    Qwilfish,
    Scizor,
    Shuckle,
    Heracross,
    Sneasel,
    Teddiursa,
    Ursaring,
    Slugma,
    Magcargo,
    Swinub,
    Piloswine,
    Corsola,
    Remoraid,
    Octillery,
    Delibird,
    Mantine,
    Skarmory,
    Houndour,
    Houndoom,
    Kingdra,
    Phanpy,
    Donphan,
    Porygon2,
    Stantler,
    Smeargle,
    Tyrogue,
    Hitmontop,
    Smoochum,
    Elekid,
    Magby,
    Miltank,
    Blissey,
    Raikou,
    Entei,
    Suicune,
    Larvitar,
    Pupitar,
    Tyranitar,
    Lugia,
    Ho_oh,
    Celebi,
    Treecko,
    Grovyle,
    Sceptile,
    Torchic,
    Combusken,
    Blaziken,
    Mudkip,
    Marshtomp,
    Swampert,
    Poochyena,
    Mightyena,
    Zigzagoon,
    Linoone,
    Wurmple,
    Silcoon,
    Beautifly,
    Cascoon,
    Dustox,
    Lotad,
    Lombre,
    Ludicolo,
    Seedot,
    Nuzleaf,
    Shiftry,
    Taillow,
    Swellow,
    Wingull,
    Pelipper,
    Ralts,
    Kirlia,
    Gardevoir,
    Surskit,
    Masquerain,
    Shroomish,
    Breloom,
    Slakoth,
    Vigoroth,
    Slaking,
    Nincada,
    Ninjask,
    Shedinja,
    Whismur,
    Loudred,
    Exploud,
    Makuhita,
    Hariyama,
    Azurill,
    Nosepass,
    Skitty,
    Delcatty,
    Sableye,
    Mawile,
    Aron,
    Lairon,
    Aggron,
    Meditite,
    Medicham,
    Electrike,
    Manectric,
    Plusle,
    Minun,
    Volbeat,
    Illumise,
    Roselia,
    Gulpin,
    Swalot,
    Carvanha,
    Sharpedo,
    Wailmer,
    Wailord,
    Numel,
    Camerupt,
    Torkoal,
    Spoink,
    Grumpig,
    Spinda,
    Trapinch,
    Vibrava,
    Flygon,
    Cacnea,
    Cacturne,
    Swablu,
    Altaria,
    Zangoose,
    Seviper,
    Lunatone,
    Solrock,
    Barboach,
    Whiscash,
    Corphish,
    Crawdaunt,
    Baltoy,
    Claydol,
    Lileep,
    Cradily,
    Anorith,
    Armaldo,
    Feebas,
    Milotic,
    Castform,
    Kecleon,
    Shuppet,
    Banette,
    Duskull,
    Dusclops,
    Tropius,
    Chimecho,
    Absol,
    Wynaut,
    Snorunt,
    Glalie,
    Spheal,
    Sealeo,
    Walrein,
    Clamperl,
    Huntail,
    Gorebyss,
    Relicanth,
    Luvdisc,
    Bagon,
    Shelgon,
    Salamence,
    Beldum,
    Metang,
    Metagross,
    Regirock,
    Regice,
    Registeel,
    Latias,
    Latios,
    Kyogre,
    Groudon,
    Rayquaza,
    Jirachi,
    Deoxys,
    Deoxys_Attack,
    Deoxys_Defense,
    Deoxys_Speed,
    Turtwig,
    Grotle,
    Torterra,
    Chimchar,
    Monferno,
    Infernape,
    Piplup,
    Prinplup,
    Empoleon,
    Starly,
    Staravia,
    Staraptor,
    Bidoof,
    Bibarel,
    Kricketot,
    Kricketune,
    Shinx,
    Luxio,
    Luxray,
    Budew,
    Roserade,
    Cranidos,
    Rampardos,
    Shieldon,
    Bastiodon,
    Burmy,
    Wormadam_Plant_Cloak,
    Wormadam_Sandy_Cloak,
    Wormadam_Trash_Cloak,
    Mothim,
    Combee,
    Vespiquen,
    Pachirisu,
    Buizel,
    Floatzel,
    Cherubi,
    Cherrim,
    Shellos_East_Coast,
    Shellos,
    Gastrodon_East_Coast,
    Gastrodon,
    Ambipom,
    Drifloon,
    Drifblim,
    Buneary,
    Lopunny,
    Mismagius,
    Honchkrow,
    Glameow,
    Purugly,
    Chingling,
    Stunky,
    Skuntank,
    Bronzor,
    Bronzong,
    Bonsly,
    Mime_Jr,
    Happiny,
    Chatot,
    Spiritomb,
    Gible,
    Gabite,
    Garchomp,
    Munchlax,
    Riolu,
    Lucario,
    Hippopotas,
    Hippowdon,
    Skorupi,
    Drapion,
    Croagunk,
    Toxicroak,
    Carnivine,
    Finneon,
    Lumineon,
    Mantyke,
    Snover,
    Abomasnow,
    Weavile,
    Magnezone,
    Lickilicky,
    Rhyperior,
    Tangrowth,
    Electivire,
    Magmortar,
    Togekiss,
    Yanmega,
    Leafeon,
    Glaceon,
    Gliscor,
    Mamoswine,
    Porygon_Z,
    Gallade,
    Probopass,
    Dusknoir,
    Froslass,
    Rotom,
    Rotom_Heat,
    Rotom_Wash,
    Rotom_Frost,
    Rotom_Fan,
    Rotom_Mow,
    Uxie,
    Mesprit,
    Azelf,
    Dialga,
    Palkia,
    Heatran,
    Regigigas,
    Giratina,
    Giratina_Origin,
    Cresselia,
    Phione,
    Manaphy,
    Darkrai,
    Shaymin,
    Shaymin_Sky,
    Arceus,
    Victini,
    Snivy,
    Servine,
    Serperior,
    Tepig,
    Pignite,
    Emboar,
    Oshawott,
    Dewott,
    Samurott,
    Patrat,
    Watchog,
    Lillipup,
    Herdier,
    Stoutland,
    Purrloin,
    Liepard,
    Pansage,
    Simisage,
    Pansear,
    Simisear,
    Panpour,
    Simipour,
    Munna,
    Musharna,
    Pidove,
    Tranquill,
    Unfezant,
    Blitzle,
    Zebstrika,
    Roggenrola,
    Boldore,
    Gigalith,
    Woobat,
    Swoobat,
    Drilbur,
    Excadrill,
    Audino,
    Timburr,
    Gurdurr,
    Conkeldurr,
    Tympole,
    Palpitoad,
    Seismitoad,
    Throh,
    Sawk,
    Sewaddle,
    Swadloon,
    Leavanny,
    Venipede,
    Whirlipede,
    Scolipede,
    Cottonee,
    Whimsicott,
    Petilil,
    Lilligant,
    Basculin,
    Sandile,
    Krokorok,
    Krookodile,
    Darumaka,
    Darmanitan,
    Maractus,
    Dwebble,
    Crustle,
    Scraggy,
    Scrafty,
    Sigilyph,
    Yamask,
    Cofagrigus,
    Tirtouga,
    Carracosta,
    Archen,
    Archeops,
    Trubbish,
    Garbodor,
    Zorua,
    Zoroark,
    Minccino,
    Cinccino,
    Gothita,
    Gothorita,
    Gothitelle,
    Solosis,
    Duosion,
    Reuniclus,
    Ducklett,
    Swanna,
    Vanillite,
    Vanillish,
    Vanilluxe,
    Deerling,
    Sawsbuck,
    Emolga,
    Karrablast,
    Escavalier,
    Foongus,
    Amoonguss,
    Frillish,
    Jellicent,
    Alomomola,
    Joltik,
    Galvantula,
    Ferroseed,
    Ferrothorn,
    Klink,
    Klang,
    Klinklang,
    Tynamo,
    Eelektrik,
    Eelektross,
    Elgyem,
    Beheeyem,
    Litwick,
    Lampent,
    Chandelure,
    Axew,
    Fraxure,
    Haxorus,
    Cubchoo,
    Beartic,
    Cryogonal,
    Shelmet,
    Accelgor,
    Stunfisk,
    Mienfoo,
    Mienshao,
    Druddigon,
    Golett,
    Golurk,
    Pawniard,
    Bisharp,
    Bouffalant,
    Rufflet,
    Braviary,
    Vullaby,
    Mandibuzz,
    Heatmor,
    Durant,
    Deino,
    Zweilous,
    Hydreigon,
    Larvesta,
    Volcarona,
    Cobalion,
    Terrakion,
    Virizion,
    Tornadus,
    Tornadus_Therian,
    Thundurus,
    Thundurus_Therian,
    Reshiram,
    Zekrom,
    Landorus,
    Landorus_Therian,
    Kyurem,
    Keldeo,
    Keldeo_Resolute,
    Meloetta,
    Genesect,
    Chespin,
    Quilladin,
    Chesnaught,
    Fennekin,
    Braixen,
    Delphox,
    Froakie,
    Frogadier,
    Greninja,
    Bunnelby,
    Diggersby,
    Fletchling,
    Fletchinder,
    Talonflame,
    Scatterbug,
    Spewpa,
    Vivillon,
    Litleo,
    Pyroar,
    Flabebe,
    Floette,
    Florges,
    Skiddo,
    Gogoat,
    Pancham,
    Pangoro,
    Furfrou,
    Espurr,
    Meowstic,
    Meowstic_Female,
    Honedge,
    Doublade,
    Aegislash,
    Spritzee,
    Aromatisse,
    Swirlix,
    Slurpuff,
    Inkay,
    Malamar,
    Binacle,
    Barbaracle,
    Skrelp,
    Dragalge,
    Clauncher,
    Clawitzer,
    Helioptile,
    Heliolisk,
    Tyrunt,
    Tyrantrum,
    Amaura,
    Aurorus,
    Sylveon,
    Hawlucha,
    Dedenne,
    Carbink,
    Goomy,
    Sliggoo,
    Goodra,
    Klefki,
    Phantump,
    Trevenant,
    Pumpkaboo,
    Gourgeist,
    Bergmite,
    Avalugg,
    Noibat,
    Noivern,
    Xerneas,
    Yveltal,
    Zygarde,
    Diancie,
    Hoopa,
    Hoopa_Unbound,
    Volcanion,
    Rowlet,
    Dartrix,
    Decidueye,
    Litten,
    Torracat,
    Incineroar,
    Popplio,
    Brionne,
    Primarina,
    Pikipek,
    Trumbeak,
    Toucannon,
    Yungoos,
    Gumshoos,
    Grubbin,
    Charjabug,
    Vikavolt,
    Crabrawler,
    Crabominable,
    Oricorio,
    Oricorio_Pom_Pom,
    Oricorio_Pau,
    Oricorio_Sensu,
    Cutiefly,
    Ribombee,
    Rockruff,
    Lycanroc,
    Lycanroc_Midnight,
    Lycanroc_Dusk,
    Wishiwashi,
    Mareanie,
    Toxapex,
    Mudbray,
    Mudsdale,
    Dewpider,
    Araquanid,
    Fomantis,
    Lurantis,
    Morelull,
    Shiinotic,
    Salandit,
    Salazzle,
    Stufful,
    Bewear,
    Bounsweet,
    Steenee,
    Tsareena,
    Comfey,
    Oranguru,
    Passimian,
    Wimpod,
    Golisopod,
    Sandygast,
    Palossand,
    Pyukumuku,
    Type_Null,
    Silvally,
    Minior,
    Komala,
    Turtonator,
    Togedemaru,
    Mimikyu,
    Bruxish,
    Drampa,
    Dhelmise,
    Jangmo_o,
    Hakamo_o,
    Kommo_o,
    Tapu_Koko,
    Tapu_Lele,
    Tapu_Bulu,
    Tapu_Fini,
    Cosmog,
    Cosmoen,
    Solgaleo,
    Lunala,
    Nihilego,
    Buzzwole,
    Pheromosa,
    Xurkitree,
    Celesteela,
    Kartana,
    Guzzlord,
    Necrozma,
    Magearna,
    Marshadow,
    Poipole,
    Naganadel,
    Stakataka,
    Blacephalon,
    Zeraora
}

#[derive(Clone)]
pub struct PokemonStats{
    pub pokemon_id: Pokemon,
    pub pokemon_name: String,
    pub type1: Type,
    pub type2: Type,
    pub generation: i16,
    pub status: LegendStatus
}

#[derive(PartialEq)]
#[derive(Copy, Clone)]
pub enum Type{
    Normal,
    Fighting,
    Flying,
    Poison,
    Ground,
    Rock,
    Bug,
    Ghost,
    Steel,
    Fire,
    Water,
    Grass,
    Electric,
    Psychic,
    Ice,
    Dragon,
    Dark,
    Fairy,
    None
}
#[derive(PartialEq)]
#[derive(Copy, Clone)]
pub enum LegendStatus{
    Standard,
    Legendary,
    Mythical,
    Mega,
}

const LEGEND_OFFSET : i32 = 50; //Level above "possible" level where they can start appearing
const MEGA_OFFSET : i32 = 15; //Level above final stage evo where it is possible to find Mega forms in wild
const MYTHICAL_OFFSET: i32 = 55;

pub fn format_pokemon_name(pkmn_name: String) -> String{
    return format!("SPECIES_{}",pkmn_name.to_uppercase());
}
pub fn get_pokemon_data(pokemon: Pokemon, all_stats: &Vec<PokemonStats>) -> PokemonStats{
    all_stats[pokemon as usize].clone()
}
pub fn get_pokemon_data_integer(pokemon: i32,all_stats: &Vec<PokemonStats>) -> PokemonStats{
    all_stats[pokemon as usize].clone()
}
pub fn get_pokemon_from_name(pokemon_name: String,all_stats: &Vec<PokemonStats>) -> Pokemon{
    for i in 0..all_stats.len() {
        if all_stats[i].pokemon_name == pokemon_name{
            return all_stats[i].pokemon_id;
        }
        if format_pokemon_name(all_stats[i].pokemon_name.clone()) == pokemon_name{
            return  all_stats[i].pokemon_id;
        }
    }
    return Pokemon::Bulbasaur;
}
pub fn read_all_pokemon() -> Vec<PokemonStats>{
    let csv: String = fs::read_to_string("data/emerald/pokemon.csv").unwrap();
    let mut reader = csv::Reader::from_reader(csv.as_bytes());
    let mut all_stats: Vec<PokemonStats> = Vec::new();
    let mut cur_num = 0;
    for cur_pokemon in reader.records(){
        if cur_num == Pokemon::Volcanion as i32{
            println!("End of file");
            break;
        }
        let cur_pokemon = cur_pokemon.unwrap();
        println!("{}",cur_pokemon[0].to_string());
        let add_pokemon = PokemonStats{
            pokemon_id: Pokemon::try_from(cur_num).unwrap(),
            pokemon_name: cur_pokemon[0].to_string(),
            type1: string_to_type(cur_pokemon[1].to_string()),
            type2: string_to_type(cur_pokemon[2].to_string()),
            generation: cur_pokemon[3].to_string().parse::<i16>().unwrap(),
            status: string_to_legend_status(cur_pokemon[4].to_string())
        };
        all_stats.push(add_pokemon);
        cur_num += 1;
    }
    all_stats
}

fn string_to_type(pkmn_type: String) -> Type{
    match pkmn_type.as_str(){
        "Normal" => Type::Grass,
        "Fighting" => Type::Fighting,
        "Flying" => Type::Flying,
        "Poison" => Type::Poison,
        "Ground" => Type::Ground,
        "Rock" => Type::Rock,
        "Bug" => Type::Bug,
        "Ghost" => Type::Ghost,
        "Steel" => Type::Steel,
        "Fire" => Type::Fire,
        "Water" => Type::Water,
        "Grass" => Type::Grass,
        "Electric" => Type::Electric,
        "Psychic" => Type::Psychic,
        "Ice" => Type::Ice,
        "Dragon" => Type::Dragon,
        "Dark" => Type::Dark,
        "Fairy" => Type::Fairy,
        _ => Type::None
    }
}
fn string_to_legend_status(pkmn_stats: String) -> LegendStatus{
    match pkmn_stats.as_str(){
        "TRUE" => LegendStatus::Legendary,
        "FALSE" => LegendStatus::Standard,
        "MEGA" => LegendStatus::Mega,
        _ => LegendStatus::Standard
    }
}

//Gen3 File Example: SPECIES_WURMPLE
//add SPECIES_ and then set name to uppercase
/*pub const LIST_OF_POKEMON : [Pokemon; 144-50] = [ //Update this number if List Expands (first line number - last line number)
    Pokemon {name: "Bulbasaur",type1: Grass,type2: Poison,evo_stage:1,total_stages: 3,status: Standard,generation: 1},
    Pokemon {name: "Ivysaur",type1: Grass, type2: Poison, evo_stage: 2, total_stages: 3, status: Standard, generation: 1},
    Pokemon {name: "Venusaur", type1: Grass, type2: Poison, evo_stage: 3, total_stages: 3, status: Standard, generation: 1},
    Pokemon {name: "Venusaur_Mega",type1: Grass, type2: Poison, evo_stage: 3, total_stages: 3, status: Mega, generation: 6},
    Pokemon {name: "Charmander",type1: Fire, type2:None,evo_stage:1,total_stages:3,status: Standard, generation: 1},
    Pokemon {name: "Charmeleon",type1: Fire, type2: None, evo_stage: 2, total_stages: 3, status: Standard, generation:1},
    Pokemon {name: "Charizard",type1: Fire, type2: Flying, evo_stage: 3, total_stages: 3, status: Standard, generation:1},
    Pokemon {name: "Charizard_Mega_X",type1: Fire, type2: Dragon,evo_stage:3,total_stages:3,status:Mega,generation:6},
    Pokemon {name: "Charizard_Mega_Y",type1: Fire,type2: Flying, evo_stage:3, total_stages:3,status:Mega,generation:6},
    Pokemon {name: "Squirtle",type1:Water,type2:None,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Wartortle",type1:Water,type2:None,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Blastoise",type1:Water,type2:None,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Blastoise_Mega",type1:Water,type2:None,evo_stage:3,total_stages:3,status:Mega,generation:6},
    Pokemon {name: "Caterpie",type1:Bug,type2:None,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Metapod",type1:Bug,type2:None,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Butterfree",type1:Bug,type2:Flying,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Weedle",type1:Bug,type2:Poison,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Kakuna",type1:Bug,type2:Poison,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Beedrill",type1:Bug,type2:Poison,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Beedrill_Mega",type1:Bug,type2:Poison,evo_stage:3,total_stages:3,status:Mega,generation:6},
    Pokemon {name: "Pidgey",type1:Normal,type2:Flying,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Pidgeotto",type1:Normal,type2:Flying,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Pidgeot",type1: Normal,type2:Flying,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Pidgeot_Mega",type1:Normal,type2:Flying,evo_stage:3,total_stages:3,status:Mega,generation:6},
    Pokemon {name: "Rattata",type1:Normal,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Rattata_Alolan",type1:Dark,type2:Normal,evo_stage:1,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Raticate",type1: Normal,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Raticate_Alolan",type1:Dark,type2:Normal,evo_stage:2,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Spearow",type1:Normal,type2:Flying,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Fearow",type1: Normal,type2:Flying,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Ekans",type1: Poison,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Arbok",type1:Poison,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Pikachu",type1:Electric,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Raichu",type1:Electric,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Raichu_Alolan",type1:Electric,type2:Psychic,evo_stage:2,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Sandshrew",type1: Ground, type2: None, evo_stage: 1, total_stages: 2, status: Standard,generation:1},
    Pokemon {name: "Sandshrew_Alolan",type1:Ice,type2:Steel,evo_stage:1,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Sandslash",type1:Ground,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Sandslash_Alolan",type1:Ice,type2:Steel,evo_stage:2,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Nidoran_F",type1: Poison,type2: None,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Nidorina",type1:Poison,type2:None,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Nidoqueen", type1:Poison,type2:Ground,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Nidoran_M",type1: Poison,type2:None,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Nidorino",type1:Poison,type2:None,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Nidoking",type1:Poison,type2:Ground,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Clefairy",type1:Fairy,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Clefable",type1:Fairy,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Vulpix",type1:Fire,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Vulpix_Alolan",type1:Ice,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Ninetales",type1:Fire,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Ninetales_Alolan",type1:Ice,type2:Fairy,evo_stage:2,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Jigglypuff",type1:Normal,type2:Fairy,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Wigglytuff",type1: Normal,type2:Fairy,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Zubat",type1:Poison,type2:Flying,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Golbat",type1:Poison,type2:Flying,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Oddish",type1:Grass,type2:Poison,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Gloom",type1:Grass,type2:Poison,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Vileplume",type1: Grass,type2: Poison,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Paras",type1:Bug,type2:Grass,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Parasect",type1:Bug,type2:Grass,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Venonat",type1:Bug,type2:Poison,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Venomoth",type1:Bug,type2:Poison,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Diglett",type1:Ground,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Diglett_Alolan",type1:Ground,type2:Steel,evo_stage:1,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Dugtrio",type1:Ground,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Dugtrio_Alolan",type1:Ground,type2:Steel,evo_stage:2,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Meowth",type1:Normal,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Meowth_Alolan",type1:Dark,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Meowth_Galarian",type1:Steel,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:8},
    Pokemon {name: "Persian",type1:Normal,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Persian_Alolan",type1:Dark,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:7},
    Pokemon {name: "Psyduck",type1:Water,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Golduck",type1: Water,type2: None, evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Mankey",type1:Fighting,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Primeape",type1:Fighting,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Growlithe",type1:Fire,type2:None,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Growlithe_Hisuian",type1:Fire,type2:Rock,evo_stage:1,total_stages:2,status:Standard,generation:8},
    Pokemon {name: "Arcanine",type1:Fire,type2:None,evo_stage:2,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Arcanine_Hisuian",type1:Fire,type2:Rock,evo_stage:2,total_stages:2,status:Standard,generation:8},
    Pokemon {name: "Poliwag",type1:Water,type2:None,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Poliwhirl",type1:Water,type2:None,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Poliwrath",type1:Water,type2:Fighting,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Abra",type1:Psychic,type2:None,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Kadabra",type1:Psychic,type2:None,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Alakazam",type1:Psychic,type2:None,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Alakazam_Mega",type1:Psychic,type2:None,evo_stage:3,total_stages:3,status:Mega,generation:6},
    Pokemon {name: "Machop",type1:Fighting,type2:None,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Machoke",type1:Fighting,type2:None,evo_stage:2,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Machamp",type1:Fighting,type2:None,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Bellsprout",type1:Grass,type2:Poison,evo_stage:1,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Weepinbell",type1:Grass,type2:Poison,evo_stage:2, total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Victreebel",type1:Grass,type2:Poison,evo_stage:3,total_stages:3,status:Standard,generation:1},
    Pokemon {name: "Tentacool",type1:Water,type2:Poison,evo_stage:1,total_stages:2,status:Standard,generation:1},
    Pokemon {name: "Tentacruel",type1:Water,type2:Poison,evo_stage:2,total_stages:2,status:Standard,generation:1}
];*/