[package]
name = "randomizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
json = "0.12.4"
num_enum = "0.7.0"
rand = "0.8.5"
try-catch = "0.2.2"
