use std::fs;
//An... Exhastive list of every single pokemon
use Type::*;
use num_enum::TryFromPrimitive;
use std::convert::TryFrom;
use crate::src::settings;
use LegendStatus::*;
use csv::{self, Reader};
use try_catch::catch;

#[derive(Copy, Clone)]
#[derive(TryFromPrimitive)]
#[derive(PartialEq)]
#[repr(i32)]
pub enum Pokemon{
    Bulbasaur,
    Ivysaur,
    Venusaur,
    VenusaurMega,
    Charmander,
    Charmeleon,
    Charizard,
    CharizardMegaX,
    CharizardMegaY,
    Squirtle,
    Wartortle,
    Blastoise,
    BlastoiseMega,
    Caterpie,
    Metapod,
    Butterfree,
    Weedle,
    Kakuna,
    Beedrill,
    BeedrillMega,
    Pidgey,
    Pidgeotto,
    Pidgeot,
    PidgeotMega,
    Rattata,
    RattataAlolan,
    Raticate,
    RaticateAlolan,
    Spearow,
    Fearow,
    Ekans,
    Arbok,
    Pikachu,
    Raichu,
    RaichuAlolan,
    Sandshrew,
    SandshrewAlolan,
    Sandslash,
    SandslashAlolan,
    NidoranF,
    Nidorina,
    Nidoqueen,
    NidoranM,
    Nidorino,
    Nidoking,
    Clefairy,
    Clefable,
    Vulpix,
    VulpixAlolan,
    Ninetales,
    NinetalesAlolan,
    Jigglypuff,
    Wigglytuff,
    Zubat,
    Golbat,
    Oddish,
    Gloom,
    Vileplume,
    Paras,
    Parasect,
    Venonat,
    Venomoth,
    Diglett,
    DiglettAlolan,
    Dugtrio,
    DugtrioAlolan,
    Meowth,
    MeowthAlolan,
    MeowthGalarian,
    Persian,
    PersianAlolan,
    Psyduck,
    Golduck,
    Mankey,
    Primeape,
    Growlithe,
    GrowlitheHisuian,
    Arcanine,
    ArcanineHisuian,
    Poliwag,
    Poliwhirl,
    Poliwrath,
    Abra,
    Kadabra,
    Alakazam,
    AlakazamMega,
    Machop,
    Machoke,
    Machamp,
    Bellsprout,
    Weepinbell,
    Victreebel,
    Tentacool,
    Tentacruel,
    Geodude,
    GeodudeAlolan,
    Graveler,
    GravelerAlolan,
    Golem,
    GolemAlolan,
    Ponyta,
    PonytaGalarian,
    Rapidash,
    RapidashGalarian,
    Slowpoke,
    SlowpokeGalarian,
    Slowbro,
    SlowbroGalarian,
    SlowbroMega,
    Magnemite,
    Magneton,
    Farfetchd,
    FarfetchdGalarian,
    Doduo,
    Dodrio,
    Seel,
    Dewgong,
    Grimer,
    GrimerAlolan,
    Muk,
    MukAlolan,
    Shellder,
    Cloyster,
    Gastly,
    Haunter,
    Gengar,
    GengarMega,
    Onix,
    Drowzee,
    Hypno,
    Krabby,
    Kingler,
    Voltorb,
    VoltorbHisuian,
    Electrode,
    ElectrodeHisuian,
    Exeggcute,
    Exeggutor,
    ExeggutorAlolan,
    Cubone,
    Marowak,
    MarowakAlolan,
    Hitmonlee,
    Hitmonchan,
    Lickitung,
    Koffing,
    Weezing,
    WeezingGalarian,
    Rhyhorn,
    Rhydon,
    Chansey,
    Tangela,
    Kangaskhan,
    KangaskhanMega,
    Horsea,
    Seadra,
    Goldeen,
    Seaking,
    Staryu,
    Starmie,
    MrMime,
    MrMimeGalarian,
    Scyther,
    Jynx,
    Electabuzz,
    Magmar,
    Pinsir,
    PinsirMega,
    Tauros,
    TAUROSPALDEANCOMBATBREED,
    TAUROSPALDEANBLAZEBREED,
    TAUROSPALDEANAQUABREED,
    Magikarp,
    Gyarados,
    GyaradosMega,
    Lapras,
    Ditto,
    Eevee,
    Vaporeon,
    Jolteon,
    Flareon,
    Porygon,
    Omanyte,
    Omastar,
    Kabuto,
    Kabutops,
    Aerodactyl,
    AerodactylMega,
    Snorlax,
    Articuno,
    ArticunoGalarian,
    Zapdos,
    ZapdosGalarian,
    Moltres,
    MoltresGalarian,
    Dratini,
    Dragonair,
    Dragonite,
    MewTwo,
    MewTwoMegaX,
    MewTwoMegaY,
    Mew,
    Chikorita,
    Bayleef,
    Meganium,
    Cyndaquil,
    Quilava,
    Typhlosion,
    TyphlosionHisuian,
    Totodile,
    Croconaw,
    Feraligatr,
    Sentret,
    Furret,
    Hoothoot,
    Noctowl,
    Ledyba,
    Ledian,
    Spinarak,
    Ariados,
    Crobat,
    Chinchou,
    Lanturn,
    Pichu,
    Cleffa,
    Igglybuff,
    Togepi,
    Togetic,
    Natu,
    Xatu,
    Mareep,
    Flaaffy,
    Ampharos,
    AmpharosMega,
    Bellossom,
    Marill,
    Azumarill,
    Sudowoodo,
    Politoed,
    Hoppip,
    Skiploom,
    Jumpluff,
    Aipom,
    Sunkern,
    Sunflora,
    Yanma,
    Wooper,
    WOOPERPALDEAN,
    Quagsire,
    Espeon,
    Umbreon,
    Murkrow,
    Slowking,
    SlowkingGalarian,
    Misdreavus,
    Unown,
    Wobbuffet,
    Girafarig,
    Pineco,
    Forretress,
    Dunsparce,
    Gligar,
    Steelix,
    SteelixMega,
    Snubbull,
    Granbull,
    Qwilfish,
    QwilfishHisuian,
    Scizor,
    ScizorMega,
    Shuckle,
    Heracross,
    HeracrossMega,
    Sneasel,
    SneaselHisuian,
    Teddiursa,
    Ursaring,
    Slugma,
    Magcargo,
    Swinub,
    Piloswine,
    Corsola,
    CorsolaGalarian,
    Remoraid,
    Octillery,
    Delibird,
    Mantine,
    Skarmory,
    Houndour,
    Houndoom,
    HoundoomMega,
    Kingdra,
    Phanpy,
    Donphan,
    Porygon2,
    Stantler,
    Smeargle,
    Tyrogue,
    Hitmontop,
    Smoochum,
    Elekid,
    Magby,
    Miltank,
    Blissey,
    Raikou,
    Entei,
    Suicune,
    Larvitar,
    Pupitar,
    Tyranitar,
    TyranitarMega,
    Lugia,
    Hooh,
    Celebi,
    Treecko,
    Grovyle,
    Sceptile,
    SceptileMega,
    Torchic,
    Combusken,
    Blaziken,
    BlazikenMega,
    Mudkip,
    Marshtomp,
    Swampert,
    SwampertMega,
    Poochyena,
    Mightyena,
    Zigzagoon,
    ZigzagoonGalarian,
    Linoone,
    LinooneGalarian,
    Wurmple,
    Silcoon,
    Beautifly,
    Cascoon,
    Dustox,
    Lotad,
    Lombre,
    Ludicolo,
    Seedot,
    Nuzleaf,
    Shiftry,
    Taillow,
    Swellow,
    Wingull,
    Pelipper,
    Ralts,
    Kirlia,
    Gardevoir,
    GardevoirMega,
    Surskit,
    Masquerain,
    Shroomish,
    Breloom,
    Slakoth,
    Vigoroth,
    Slaking,
    Nincada,
    Ninjask,
    Shedinja,
    Whismur,
    Loudred,
    Exploud,
    Makuhita,
    Hariyama,
    Azurill,
    Nosepass,
    Skitty,
    Delcatty,
    Sableye,
    SableyeMega,
    Mawile,
    MawileMega,
    Aron,
    Lairon,
    Aggron,
    AggronMega,
    Meditite,
    Medicham,
    MedichamMega,
    Electrike,
    Manectric,
    ManectricMega,
    Plusle,
    Minun,
    Volbeat,
    Illumise,
    Roselia,
    Gulpin,
    Swalot,
    Carvanha,
    Sharpedo,
    SharpedoMega,
    Wailmer,
    Wailord,
    Numel,
    Camerupt,
    CameruptMega,
    Torkoal,
    Spoink,
    Grumpig,
    Spinda,
    Trapinch,
    Vibrava,
    Flygon,
    Cacnea,
    Cacturne,
    Swablu,
    Altaria,
    AltariaMega,
    Zangoose,
    Seviper,
    Lunatone,
    Solrock,
    Barboach,
    Whiscash,
    Corphish,
    Crawdaunt,
    Baltoy,
    Claydol,
    Lileep,
    Cradily,
    Anorith,
    Armaldo,
    Feebas,
    Milotic,
    Castform,
    Kecleon,
    Shuppet,
    Banette,
    BanetteMega,
    Duskull,
    Dusclops,
    Tropius,
    Chimecho,
    Absol,
    AbsolMega,
    Wynaut,
    Snorunt,
    Glalie,
    GlalieMega,
    Spheal,
    Sealeo,
    Walrein,
    Clamperl,
    Huntail,
    Gorebyss,
    Relicanth,
    Luvdisc,
    Bagon,
    Shelgon,
    Salamence,
    SalamenceMega,
    Beldum,
    Metang,
    Metagross,
    MetagrossMega,
    Regirock,
    Regice,
    Registeel,
    Latias,
    LatiasMega,
    Latios,
    LatiosMega,
    Kyogre,
    KyogrePrimal,
    Groudon,
    GroudonPrimal,
    Rayquaza,
    RayquazaMega,
    Jirachi,
    Deoxys,
    Turtwig,
    Grotle,
    Torterra,
    Chimchar,
    Monferno,
    Infernape,
    Piplup,
    Prinplup,
    Empoleon,
    Starly,
    Staravia,
    Staraptor,
    Bidoof,
    Bibarel,
    Kricketot,
    Kricketune,
    Shinx,
    Luxio,
    Luxray,
    Budew,
    Roserade,
    Cranidos,
    Rampardos,
    Shieldon,
    Bastiodon,
    Burmy,
    Wormadam,
    Mothim,
    Combee,
    Vespiquen,
    Pachirisu,
    Buizel,
    Floatzel,
    Cherubi,
    Cherrim,
    Shellos,
    Gastrodon,
    Ambipom,
    Drifloon,
    Drifblim,
    Buneary,
    Lopunny,
    LopunnyMega,
    Mismagius,
    Honchkrow,
    Glameow,
    Purugly,
    Chingling,
    Stunky,
    Skuntank,
    Bronzor,
    Bronzong,
    Bonsly,
    MimeJr,
    Happiny,
    Chatot,
    Spiritomb,
    Gible,
    Gabite,
    Garchomp,
    GarchompMega,
    Munchlax,
    Riolu,
    Lucario,
    LucarioMega,
    Hippopotas,
    Hippowdon,
    Skorupi,
    Drapion,
    Croagunk,
    Toxicroak,
    Carnivine,
    Finneon,
    Lumineon,
    Mantyke,
    Snover,
    Abomasnow,
    AbomasnowMega,
    Weavile,
    Magnezone,
    Lickilicky,
    Rhyperior,
    Tangrowth,
    Electivire,
    Magmortar,
    Togekiss,
    Yanmega,
    Leafeon,
    Glaceon,
    Gliscor,
    Mamoswine,
    PorygonZ,
    Gallade,
    GalladeMega,
    Probopass,
    Dusknoir,
    Froslass,
    Rotom,
    RotomHeat,
    RotomWash,
    RotomFrost,
    RotomFan,
    RotomMow,
    Uxie,
    Mesprit,
    Azelf,
    Dialga,
    DialgaOrigin,
    Palkia,
    PalkiaOrigin,
    Heatran,
    Regigigas,
    Giratina,
    GiratinaOrigin,
    Cresselia,
    Phione,
    Manaphy,
    Darkrai,
    Shaymin,
    ShayminSky,
    Arceus,
    Victini,
    Snivy,
    Servine,
    Serperior,
    Tepig,
    Pignite,
    Emboar,
    Oshawott,
    Dewott,
    Samurott,
    SamurottHisuian,
    Patrat,
    Watchog,
    Lillipup,
    Herdier,
    Stoutland,
    Purrloin,
    Liepard,
    Pansage,
    Simisage,
    Pansear,
    Simisear,
    Panpour,
    Simipour,
    Munna,
    Musharna,
    Pidove,
    Tranquill,
    Unfezant,
    Blitzle,
    Zebstrika,
    Roggenrola,
    Boldore,
    Gigalith,
    Woobat,
    Swoobat,
    Drilbur,
    Excadrill,
    Audino,
    AudinoMega,
    Timburr,
    Gurdurr,
    Conkeldurr,
    Tympole,
    Palpitoad,
    Seismitoad,
    Throh,
    Sawk,
    Sewaddle,
    Swadloon,
    Leavanny,
    Venipede,
    Whirlipede,
    Scolipede,
    Cottonee,
    Whimsicott,
    Petilil,
    Lilligant,
    LilligantHisuian,
    Basculin,
    Sandile,
    Krokorok,
    Krookodile,
    Darumaka,
    DarumakaGalarian,
    Darmanitan,
    DarmanitanGalarian,
    Maractus,
    Dwebble,
    Crustle,
    Scraggy,
    Scrafty,
    Sigilyph,
    Yamask,
    YamaskGalarian,
    Cofagrigus,
    Tirtouga,
    Carracosta,
    Archen,
    Archeops,
    Trubbish,
    Garbodor,
    Zorua,
    ZoruaHisuian,
    Zoroark,
    ZoroarkHisuian,
    Minccino,
    Cinccino,
    Gothita,
    Gothorita,
    Gothitelle,
    Solosis,
    Duosion,
    Reuniclus,
    Ducklett,
    Swanna,
    Vanillite,
    Vanillish,
    Vanilluxe,
    Deerling,
    Sawsbuck,
    Emolga,
    Karrablast,
    Escavalier,
    Foongus,
    Amoonguss,
    Frillish,
    Jellicent,
    Alomomola,
    Joltik,
    Galvantula,
    Ferroseed,
    Ferrothorn,
    Klink,
    Klang,
    Klinklang,
    Tynamo,
    Eelektrik,
    Eelektross,
    Elgyem,
    Beheeyem,
    Litwick,
    Lampent,
    Chandelure,
    Axew,
    Fraxure,
    Haxorus,
    Cubchoo,
    Beartic,
    Cryogonal,
    Shelmet,
    Accelgor,
    Stunfisk,
    StunfiskGalarian,
    Mienfoo,
    Mienshao,
    Druddigon,
    Golett,
    Golurk,
    Pawniard,
    Bisharp,
    Bouffalant,
    Rufflet,
    Braviary,
    BraviaryHisuian,
    Vullaby,
    Mandibuzz,
    Heatmor,
    Durant,
    Deino,
    Zweilous,
    Hydreigon,
    Larvesta,
    Volcarona,
    Cobalion,
    Terrakion,
    Virizion,
    Tornadus,
    TornadusTherian,
    Thundurus,
    ThundurusTherian,
    Reshiram,
    Zekrom,
    Landorus,
    LandorusTherian,
    Kyurem,
    KyuremWhite,
    KyuremBlack,
    Keldeo,
    KeldeoResolute,
    Meloetta,
    Genesect,
    Chespin,
    Quilladin,
    Chesnaught,
    Fennekin,
    Braixen,
    Delphox,
    Froakie,
    Frogadier,
    Greninja,
    Bunnelby,
    Diggersby,
    Fletchling,
    Fletchinder,
    Talonflame,
    Scatterbug,
    Spewpa,
    Vivillon,
    Litleo,
    Pyroar,
    Flabebe,
    Floette,
    Florges,
    Skiddo,
    Gogoat,
    Pancham,
    Pangoro,
    Furfrou,
    Espurr,
    Meowstic,
    MeowsticFemale,
    Honedge,
    Doublade,
    Aegislash,
    Spritzee,
    Aromatisse,
    Swirlix,
    Slurpuff,
    Inkay,
    Malamar,
    Binacle,
    Barbaracle,
    Skrelp,
    Dragalge,
    Clauncher,
    Clawitzer,
    Helioptile,
    Heliolisk,
    Tyrunt,
    Tyrantrum,
    Amaura,
    Aurorus,
    Sylveon,
    Hawlucha,
    Dedenne,
    Carbink,
    Goomy,
    Sliggoo,
    SliggooHisuian,
    Goodra,
    GoodraHisuian,
    Klefki,
    Phantump,
    Trevenant,
    Pumpkaboo,
    Gourgeist,
    Bergmite,
    Avalugg,
    AvaluggHisuian,
    Noibat,
    Noivern,
    Xerneas,
    Yveltal,
    Zygarde10,
    Zygarde,
    Diancie,
    DiancieMega,
    Hoopa,
    HoopaUnbound,
    Volcanion,
    Rowlet,
    Dartrix,
    Decidueye,
    DecidueyeHisuian,
    Litten,
    Torracat,
    Incineroar,
    Popplio,
    Brionne,
    Primarina,
    Pikipek,
    Trumbeak,
    Toucannon,
    Yungoos,
    Gumshoos,
    Grubbin,
    Charjabug,
    Vikavolt,
    Crabrawler,
    Crabominable,
    OricorioBaile,
    OricorioPomPom,
    OricorioPau,
    OricorioSensu,
    Cutiefly,
    Ribombee,
    Rockruff,
    Lycanroc,
    LycanrocMidnight,
    LycanrocDusk,
    Wishiwashi,
    Mareanie,
    Toxapex,
    Mudbray,
    Mudsdale,
    Dewpider,
    Araquanid,
    Fomantis,
    Lurantis,
    Morelull,
    Shiinotic,
    Salandit,
    Salazzle,
    Stufful,
    Bewear,
    Bounsweet,
    Steenee,
    Tsareena,
    Comfey,
    Oranguru,
    Passimian,
    Wimpod,
    Golisopod,
    Sandygast,
    Palossand,
    Pyukumuku,
    TypeNull,
    Silvally,
    Minior,
    Komala,
    Turtonator,
    Togedemaru,
    Mimikyu,
    Bruxish,
    Drampa,
    Dhelmise,
    Jangmoo,
    Hakamoo,
    Kommoo,
    TapuKoko,
    TapuLele,
    TapuBulu,
    TapuFini,
    Cosmog,
    Cosmoem,
    Solgaleo,
    Lunala,
    Nihilego,
    Buzzwole,
    Pheromosa,
    Xurkitree,
    Celesteela,
    Kartana,
    Guzzlord,
    Necrozma,
    NecrozmaDuskMane,
    NecrozmaDawnWings,
    NecrozmaUltra,
    Magearna,
    Marshadow,
    Poipole,
    Naganadel,
    Stakataka,
    Blacephalon,
    Zeraora,
    Meltan,
    Melmetal,
    Grookey,
    Thwackey,
    Rillaboom,
    Scorbunny,
    Raboot,
    Cinderace,
    Sobble,
    Drizzile,
    Inteleon,
    Skwovet,
    Greedent,
    Rookidee,
    Corvisquire,
    Corviknight,
    Blipbug,
    Dottler,
    Orbeetle,
    Nickit,
    Thievul,
    Gossifleur,
    Eldegoss,
    Wooloo,
    Dubwool,
    Chewtle,
    Drednaw,
    Yamper,
    Boltund,
    Rolycoly,
    Carkol,
    Coalossal,
    Applin,
    Flapple,
    Appletun,
    Silicobra,
    Sandaconda,
    Cramorant,
    Arrokuda,
    Barraskewda,
    Toxel,
    Toxtricity,
    Sizzlipede,
    Centiskorch,
    Clobbopus,
    Grapploct,
    Sinistea,
    Polteageist,
    Hatenna,
    Hattrem,
    Hatterene,
    Impidimp,
    Morgrem,
    Grimmsnarl,
    Obstagoon,
    Perrserker,
    Cursola,
    Sirfetchd,
    MrRime,
    Runerigus,
    Milcery,
    Alcremie,
    Falinks,
    Pincurchin,
    Snom,
    Frosmoth,
    Stonjourner,
    Eiscue,
    Indeedee,
    Morpeko,
    Cufant,
    Copperajah,
    Dracozolt,
    Arctozolt,
    Dracovish,
    Arctovish,
    Duraludon,
    Dreepy,
    Drakloak,
    Dragapult,
    Zacian,
    ZacianCrownedSword,
    Zamazenta,
    ZamazentaCrownedShield,
    Eternatus,
    EternatusEternamax,
    Kubfu,
    Urshifu,
    Zarude,
    Regieleki,
    Regidrago,
    Glastrier,
    Spectrier,
    Calyrex,
    CalyrexIceRider,
    CalyrexShadowRider,
    Wyrdeer,
    Kleavor,
    Ursaluna,
    Basculegion,
    Sneasler,
    Overqwil,
    Enamorus,
    EnamorusTherian,
    Sprigatito,
    Floragato,
    Meowscarada,
    Fuecoco,
    Crocalor,
    Skeledirge,
    Quaxly,
    Quaxwell,
    Quaquaval,
    Lechonk,
    Oinkologne,
    Tarountula,
    Spidops,
    Nymble,
    Lokix,
    Pawmi,
    Pawmo,
    Pawmot,
    Tandemaus,
    Maushold,
    Fidough,
    Dachsbun,
    Smoliv,
    Dolliv,
    Arboliva,
    Squawkabilly,
    Nacli,
    Naclstack,
    Garganacl,
    Charcadet,
    Armarouge,
    Ceruledge,
    Tadbulb,
    Bellibolt,
    Wattrel,
    Kilowattrel,
    Maschiff,
    Mabosstiff,
    Shroodle,
    Grafaiai,
    Bramblin,
    Brambleghast,
    Toedscool,
    Toedscruel,
    Klawf,
    Capsakid,
    Scovillain,
    Rellor,
    Rabsca,
    Flittle,
    Espathra,
    Tinkatink,
    Tinkatuff,
    Tinkaton,
    Wiglett,
    Wugtrio,
    Bombirdier,
    Finizen,
    Palafin,
    Varoom,
    Revavroom,
    Cyclizar,
    Orthworm,
    Glimmet,
    Glimmora,
    Greavard,
    Houndstone,
    Flamigo,
    Cetoddle,
    Cetitan,
    Veluza,
    Dondozo,
    Tatsugiri,
    Annihilape,
    Clodsire,
    Farigiraf,
    Dudunsparce,
    Kingambit,
    Greattusk,
    Screamtail,
    Brutebonnet,
    Fluttermane,
    Slitherwing,
    Sandyshocks,
    Irontreads,
    Ironbundle,
    Ironhands,
    Ironjugulis,
    Ironmoth,
    Ironthorns,
    Frigibax,
    Arctibax,
    Baxcalibur,
    Gimmighoul,
    Gholdengo,
    Wochien,
    Chienpao,
    Tinglu,
    Chiyu,
    Roaringmoon,
    Ironvaliant,
    Koraidon,
    Miraidon,
    Walkingwake,
    Ironleaves,
    Dipplin,
    Poltchageist,
    Sinistcha,
    Okidogi,
    Munkidori,
    Fezandipiti,
    Ogerpon,
    Archaludon,
    Hydrapple,
    Gougingfire,
    Ragingbolt,
    Ironboulder,
    Ironcrown,
    Terapagos,
    Pecharunt,
    None,
}

#[derive(Clone)]
pub struct PokemonStats{
    pub pokemon_id: Pokemon,
    pub pokemon_name: String,
    pub type1: Type,
    pub type2: Type,
    pub generation: i16,
    pub status: LegendStatus,
    pub min_level: i16,
    pub evolve_from: Pokemon,
    pub evolve_into: Vec<Pokemon>
}

#[derive(PartialEq)]
#[derive(Copy, Clone)]
pub enum Type{
    Normal,
    Fighting,
    Flying,
    Poison,
    Ground,
    Rock,
    Bug,
    Ghost,
    Steel,
    Fire,
    Water,
    Grass,
    Electric,
    Psychic,
    Ice,
    Dragon,
    Dark,
    Fairy,
    Stellar,
    None
}
#[derive(PartialEq)]
#[derive(Copy, Clone)]
pub enum LegendStatus{
    Standard,
    Legendary,
    Mythical,
    Mega,
    LegendMega,
}

pub fn format_pokemon_name(pkmn_name: String) -> String{
    return format!("SPECIES_{}",pkmn_name.to_uppercase());
}
pub fn get_pokemon_data(pokemon: Pokemon, all_stats: &Vec<PokemonStats>) -> PokemonStats{
    all_stats[pokemon as usize].clone()
}
pub fn pokemon_to_formatted_name(pkmn: Pokemon,all_stats: &Vec<PokemonStats>) -> String{
    return format_pokemon_name(get_pokemon_data(pkmn,all_stats).pokemon_name);
}
pub fn get_pokemon_data_integer(pokemon: i32,all_stats: &Vec<PokemonStats>) -> PokemonStats{
    all_stats[pokemon as usize].clone()
}
pub fn get_pokemon_from_name(pokemon_name: String,all_stats: &Vec<PokemonStats>) -> Pokemon{
    //println!("get pokemon_{}_",pokemon_name);
    if pokemon_name == ""{
        return Pokemon::None;
    }
    for i in 0..all_stats.len() {
        if all_stats[i].pokemon_name == pokemon_name{
            return all_stats[i].pokemon_id;
        }
        if format_pokemon_name(all_stats[i].pokemon_name.clone()) == pokemon_name{
            return  all_stats[i].pokemon_id;
        }
    }
    return Pokemon::None;
}
pub fn read_all_pokemon() -> Vec<PokemonStats>{
    let csv: String = fs::read_to_string("data/emerald/pokemon.csv").unwrap();
    let mut reader = csv::Reader::from_reader(csv.as_bytes());
    let mut all_stats: Vec<PokemonStats> = Vec::new();
    let mut cur_num = 0;
    let mut evolveinto: Vec<Vec<String>> = Vec::new(); //Dumb workaround because we don't have all the pokemon loaded at first, and we need a complete pokedex before adding "Evolve intos"
    for cur_pokemon in reader.records(){
        if cur_num == Pokemon::None as i32{
            println!("End of file");
            break;
        }
        let cur_pokemon = cur_pokemon.unwrap();
        let min_level_string = cur_pokemon[5].to_string();
        let min_level = if min_level_string == "Other".to_string() || min_level_string == "Mega".to_string(){
            0
        }
        else{
            min_level_string.parse::<i16>().unwrap()
        };
        let mut next_evo = Vec::new();
        for i in 7..13{
            let next_pkmn = cur_pokemon[i].to_string();
            if next_pkmn == ""{
                break;
            }
            next_evo.push(next_pkmn);
        }
        evolveinto.push(next_evo);
        let add_pokemon = PokemonStats{
            pokemon_id: Pokemon::try_from(cur_num).unwrap(),
            pokemon_name: cur_pokemon[0].to_string(),
            type1: string_to_type(cur_pokemon[1].to_string()),
            type2: string_to_type(cur_pokemon[2].to_string()),
            generation: cur_pokemon[3].to_string().parse::<i16>().unwrap(),
            status: string_to_legend_status(cur_pokemon[4].to_string()),
            min_level: min_level,
            evolve_from: get_pokemon_from_name(cur_pokemon[6].to_string(), &all_stats),
            evolve_into: vec![Pokemon::None]
        };
        all_stats.push(add_pokemon);
        cur_num += 1;
    }
    //Go back through vector (makes this algorithm O(2n) but whatever I don't care that much)
    for cur_pokemon_index in 0..evolveinto.len(){
        let mut next_evos:Vec<Pokemon> = Vec::new();
        for cur_pokemon_next in evolveinto[cur_pokemon_index].clone(){
            next_evos.push(get_pokemon_from_name(cur_pokemon_next, &all_stats))
        }
        all_stats[cur_pokemon_index].evolve_into = next_evos;
    }
    all_stats
}

fn string_to_type(pkmn_type: String) -> Type{
    match pkmn_type.as_str(){
        "Normal" => Type::Normal,
        "Fighting" => Type::Fighting,
        "Flying" => Type::Flying,
        "Poison" => Type::Poison,
        "Ground" => Type::Ground,
        "Rock" => Type::Rock,
        "Bug" => Type::Bug,
        "Ghost" => Type::Ghost,
        "Steel" => Type::Steel,
        "Fire" => Type::Fire,
        "Water" => Type::Water,
        "Grass" => Type::Grass,
        "Electric" => Type::Electric,
        "Psychic" => Type::Psychic,
        "Ice" => Type::Ice,
        "Dragon" => Type::Dragon,
        "Dark" => Type::Dark,
        "Fairy" => Type::Fairy,
        "Stellar" => Type::Stellar,
        _ => Type::None
    }
}
pub fn type_to_string(pkmn_type: Type) -> String{
    match pkmn_type{
         Type::Normal => "Normal",
         Type::Fighting => "Fighting",
         Type::Flying => "Flying",
         Type::Poison => "Poison",
         Type::Ground => "Ground",
         Type::Rock => "Rock",
         Type::Bug => "Bug",
         Type::Ghost => "Ghost",
         Type::Steel => "Steel",
         Type::Fire => "Fire",
         Type::Water => "Water",
         Type::Grass => "Grass",
         Type::Electric => "Electric",
         Type::Psychic => "Psychic",
         Type::Ice => "Ice",
         Type::Dragon => "Dragon",
         Type::Dark => "Dark",
         Type::Fairy => "Fairy",
         Type::Stellar => "Stellar",
        _ => "Normal"
    }.to_string()
}
fn string_to_legend_status(pkmn_stats: String) -> LegendStatus{
    match pkmn_stats.as_str(){
        "TRUE" => LegendStatus::Legendary,
        "FALSE" => LegendStatus::Standard,
        "MEGA" => LegendStatus::Mega,
        "LegendMega" => LegendStatus::LegendMega,
        _ => LegendStatus::Standard
    }
}



pub fn pokemon_alternate_forms(species: Pokemon,all_stats: &Vec<PokemonStats>,settings: &mut settings::Settings) -> String{
    return match species{
        Pokemon::Pikachu => get_random_name_from_list_with_prefered(settings,vec![
            "PIKACHU".to_string(),
            "PIKACHU_COSPLAY".to_string(),
            "PIKACHU_ROCK_STAR".to_string(),
            "PIKACHU_BELLE".to_string(),
            "PIKACHU_POP_STAR".to_string(),
            "PIKACHU_PH_D".to_string(),
            "PIKACHU_LIBRE".to_string(),
            "PIKACHU_ORIGINAL_CAP".to_string(),
            "PIKACHU_HOENN_CAP".to_string(),
            "PIKACHU_SINNOH_CAP".to_string(),
            "PIKACHU_UNOVA_CAP".to_string(),
            "PIKACHU_KALOS_CAP".to_string(),
            "PIKACHU_ALOLA_CAP".to_string(),
            "PIKACHU_PARTNER_CAP".to_string(),
            "PIKACHU_WORLD_CAP".to_string()],0),
        Pokemon::Unown => get_random_name_from_list(settings,vec![
            "UNOWN".to_string(),
            "UNOWN_B".to_string(),
            "UNOWN_C".to_string(),
            "UNOWN_D".to_string(),
            "UNOWN_E".to_string(),
            "UNOWN_F".to_string(),
            "UNOWN_G".to_string(),
            "UNOWN_H".to_string(),
            "UNOWN_I".to_string(),
            "UNOWN_J".to_string(),
            "UNOWN_K".to_string(),
            "UNOWN_L".to_string(),
            "UNOWN_M".to_string(),
            "UNOWN_N".to_string(),
            "UNOWN_O".to_string(),
            "UNOWN_P".to_string(),
            "UNOWN_Q".to_string(),
            "UNOWN_R".to_string(),
            "UNOWN_S".to_string(),
            "UNOWN_T".to_string(),
            "UNOWN_U".to_string(),
            "UNOWN_V".to_string(),
            "UNOWN_W".to_string(),
            "UNOWN_X".to_string(),
            "UNOWN_Y".to_string(),
            "UNOWN_Z".to_string(),
            "UNOWN_EMARK".to_string(),
            "UNOWN_QMARK".to_string()
        ]),
        Pokemon::Deoxys => get_random_name_from_list(settings,vec![
            "DEOXYS_NORMAL".to_string(),
            "DEOXYS_ATTACK".to_string(),
            "DEOXYS_DEFENSE".to_string(),
            "DEOXYS_SPEED".to_string()
        ]),
        Pokemon::Burmy => get_random_name_from_list(settings,vec![
            "BURMY_PLANT_CLOAK".to_string(),
            "BURMY_SANDY_CLOAK".to_string(),
            "BURMY_TRASH_CLOAK".to_string()
        ]),
        Pokemon::Wormadam => get_random_name_from_list(settings,vec![
            "WORMADAM_PLANT_CLOAK".to_string(),
            "WORMADAM_SANDY_CLOAK".to_string(),
            "WORMADAM_TRASH_CLOAK".to_string()
        ]),
        Pokemon::Mothim => get_random_name_from_list(settings,vec![
            "MOTHIM_PLANT_CLOAK".to_string(),
            "MOTHIM_SANDY_CLOAK".to_string(),
            "MOTHIM_TRASH_CLOAK".to_string()
        ]),
        Pokemon::Shellos => get_random_name_from_list(settings,vec![
            "SHELLOS_EAST_SEA".to_string(),
            "SHELLOS_WEST_SEA".to_string()
        ]),
        Pokemon::Gastrodon => get_random_name_from_list(settings,vec![
            "GASTRODON_EAST_SEA".to_string(),
            "GASTRODON_WEST_SEA".to_string()
        ]),
        Pokemon::Shaymin => get_random_name_from_list(settings,vec![
            "SHAYMIN_SKY".to_string(),
            "SHAYMIN_LAND".to_string()
        ]),
        Pokemon::Basculin => get_random_name_from_list(settings,vec![
            "BASCULIN_RED_STRIPED".to_string(),
            "BASCULIN_BLUE_STRIPED".to_string(),
            "BASCULIN_WHITE_STRIPED".to_string()
        ]),
        Pokemon::Deerling => get_random_name_from_list(settings,vec![
            "DEERLING_SPRING".to_string(),
            "DEERLING_SUMMER".to_string(),
            "DEERLING_AUTUMN".to_string(),
            "DEERLING_WINTER".to_string()
        ]),
        Pokemon::Sawsbuck => get_random_name_from_list(settings,vec![
            "SAWSBUCK_SPRING".to_string(),
            "SAWSBUCK_SUMMER".to_string(),
            "SAWSBUCK_AUTUMN".to_string(),
            "SAWSBUCK_WINTER".to_string()
        ]),
        Pokemon::Greninja => get_random_name_from_list_with_prefered(settings,vec![
            "GRENINJA".to_string(),
            "GRENINJA_BATTLE_BOND".to_string()
        ],0),
        Pokemon::Vivillon => get_random_name_from_list(settings,vec![
            "VIVILLON_ICY_SNOW".to_string(),
            "VIVILLON_POLAR".to_string(),
            "VIVILLON_TUNDRA".to_string(),
            "VIVILLON_CONTINENTAL".to_string(),
            "VIVILLON_GARDEN".to_string(),
            "VIVILLON_ELEGANT".to_string(),
            "VIVILLON_MEADOW".to_string(),
            "VIVILLON_MODERN".to_string(),
            "VIVILLON_MARINE".to_string(),
            "VIVILLON_ARCHIPELAGO".to_string(),
            "VIVILLON_HIGH_PLAINS".to_string(),
            "VIVILLON_SANDSTORM".to_string(),
            "VIVILLON_RIVER".to_string(),
            "VIVILLON_MONSOON".to_string(),
            "VIVILLON_SAVANNA".to_string(),
            "VIVILLON_SUN".to_string(),
            "VIVILLON_OCEAN".to_string(),
            "VIVILLON_JUNGLE".to_string(),
            "VIVILLON_FANCY".to_string(),
            "VIVILLON_POKE_BALL".to_string()
        ]),
        Pokemon::Spewpa => get_random_name_from_list(settings,vec![
            "SPEWPA_ICY_SNOW".to_string(),
            "SPEWPA_POLAR".to_string(),
            "SPEWPA_TUNDRA".to_string(),
            "SPEWPA_CONTINENTAL".to_string(),
            "SPEWPA_GARDEN".to_string(),
            "SPEWPA_ELEGANT".to_string(),
            "SPEWPA_MEADOW".to_string(),
            "SPEWPA_MODERN".to_string(),
            "SPEWPA_MARINE".to_string(),
            "SPEWPA_ARCHIPELAGO".to_string(),
            "SPEWPA_HIGH_PLAINS".to_string(),
            "SPEWPA_SANDSTORM".to_string(),
            "SPEWPA_RIVER".to_string(),
            "SPEWPA_MONSOON".to_string(),
            "SPEWPA_SAVANNA".to_string(),
            "SPEWPA_SUN".to_string(),
            "SPEWPA_OCEAN".to_string(),
            "SPEWPA_JUNGLE".to_string(),
            "SPEWPA_FANCY".to_string(),
            "SPEWPA_POKE_BALL".to_string()
        ]),
        Pokemon::Scatterbug => get_random_name_from_list(settings,vec![
            "SCATTERBUG_ICY_SNOW".to_string(),
            "SCATTERBUG_POLAR".to_string(),
            "SCATTERBUG_TUNDRA".to_string(),
            "SCATTERBUG_CONTINENTAL".to_string(),
            "SCATTERBUG_GARDEN".to_string(),
            "SCATTERBUG_ELEGANT".to_string(),
            "SCATTERBUG_MEADOW".to_string(),
            "SCATTERBUG_MODERN".to_string(),
            "SCATTERBUG_MARINE".to_string(),
            "SCATTERBUG_ARCHIPELAGO".to_string(),
            "SCATTERBUG_HIGH_PLAINS".to_string(),
            "SCATTERBUG_SANDSTORM".to_string(),
            "SCATTERBUG_RIVER".to_string(),
            "SCATTERBUG_MONSOON".to_string(),
            "SCATTERBUG_SAVANNA".to_string(),
            "SCATTERBUG_SUN".to_string(),
            "SCATTERBUG_OCEAN".to_string(),
            "SCATTERBUG_JUNGLE".to_string(),
            "SCATTERBUG_FANCY".to_string(),
            "SCATTERBUG_POKE_BALL".to_string()
        ]),
        Pokemon::Flabebe => get_random_name_from_list(settings,vec![
            "FLABEBE_RED_FLOWER".to_string(),
            "FLABEBE_YELLOW_FLOWER".to_string(),
            "FLABEBE_ORANGE_FLOWER".to_string(),
            "FLABEBE_BLUE_FLOWER".to_string(),
            "FLABEBE_WHITE_FLOWER".to_string()
        ]),
        Pokemon::Floette => get_random_name_from_list(settings,vec![
            "FLOETTE_RED_FLOWER".to_string(),
            "FLOETTE_YELLOW_FLOWER".to_string(),
            "FLOETTE_ORANGE_FLOWER".to_string(),
            "FLOETTE_BLUE_FLOWER".to_string(),
            "FLOETTE_WHITE_FLOWER".to_string(),
            "FLOETTE_ETERNAL_FLOWER".to_string()
        ]),
        Pokemon::Florges => get_random_name_from_list(settings,vec![
            "FLORGES_RED_FLOWER".to_string(),
            "FLORGES_YELLOW_FLOWER".to_string(),
            "FLORGES_ORANGE_FLOWER".to_string(),
            "FLORGES_BLUE_FLOWER".to_string(),
            "FLORGES_WHITE_FLOWER".to_string()
        ]),
        Pokemon::Furfrou => get_random_name_from_list(settings,vec![
            "FURFROU_NATURAL".to_string(),
            "FURFROU_HEART_TRIM".to_string(),
            "FURFROU_STAR_TRIM".to_string(),
            "FURFROU_DIAMOND_TRIM".to_string(),
            "FURFROU_DEBUTANTE_TRIM".to_string(),
            "FURFROU_MATRON_TRIM".to_string(),
            "FURFROU_DANDY_TRIM".to_string(),
            "FURFROU_LA_REINE_TRIM".to_string(),
            "FURFROU_KABUKI_TRIM".to_string(),
            "FURFROU_PHARAOH_TRIM".to_string()
        ]),
        Pokemon::Pumpkaboo => get_random_name_from_list(settings,vec![
            "PUMPKABOO_SMALL".to_string(),
            "PUMPKABOO_AVERAGE".to_string(),
            "PUMPKABOO_LARGE".to_string(),
            "PUMPKABOO_SUPER".to_string()
        ]),
        Pokemon::Gourgeist => get_random_name_from_list(settings,vec![
            "GOURGEIST_SMALL".to_string(),
            "GOURGEIST_AVERAGE".to_string(),
            "GOURGEIST_LARGE".to_string(),
            "GOURGEIST_SUPER".to_string()
        ]),
        Pokemon::Zygarde10 => get_random_name_from_list(settings,vec![
            "ZYGARDE_10_AURA_BREAK".to_string(),
            "ZYGARDE_10_POWER_CONSTRUCT".to_string()
        ]),
        Pokemon::Zygarde => get_random_name_from_list(settings,vec![
            "ZYGARDE_50_AURA_BREAK".to_string(),
            "ZYGARDE_50_POWER_CONSTRUCT".to_string()
        ]),
        Pokemon::Rockruff => get_random_name_from_list_with_prefered(settings,vec![
            "ROCKRUFF".to_string(),
            "ROCKRUFF_OWN_TEMPO".to_string()
        ],0),
        Pokemon::Lycanroc => get_random_name_from_list(settings,vec![
            "LYCANROC_MIDNIGHT".to_string(),
            "LYCANROC_DUSK".to_string()
        ]),
        Pokemon::Minior => get_random_name_from_list(settings,vec![
            "MINIOR_ORANGE".to_string(),
            "MINIOR_YELLOW".to_string(),
            "MINIOR_GREEN".to_string(),
            "MINIOR_BLUE".to_string(),
            "MINIOR_INDIGO".to_string(),
            "MINIOR_VIOLET".to_string()
        ]),
        Pokemon::Magearna => get_random_name_from_list(settings,vec![
            "MAGEARNA".to_string(),
            "MAGEARNA_ORIGINAL_COLOR".to_string()
        ]),
        Pokemon::Toxtricity => get_random_name_from_list(settings,vec![
            "TOXTRICITY_AMPED".to_string(),
            "TOXTRICITY_LOW_KEY".to_string()
        ]),
        Pokemon::Sinistea => get_random_name_from_list_with_prefered(settings,vec![
            "SINISTEA_PHONY".to_string(),
            "SINISTEA_ANTIQUE".to_string()
        ],0),
        Pokemon::Polteageist => get_random_name_from_list_with_prefered(settings,vec![
            "POLTEAGEIST_PHONY".to_string(),
            "POLTEAGEIST_ANTIQUE".to_string()
        ],0),
        Pokemon::Alcremie => get_random_name_from_list(settings,vec![
            "ALCREMIE_RUBY_CREAM".to_string(),
            "ALCREMIE_MATCHA_CREAM".to_string(),
            "ALCREMIE_MINT_CREAM".to_string(),
            "ALCREMIE_LEMON_CREAM".to_string(),
            "ALCREMIE_SALTED_CREAM".to_string(),
            "ALCREMIE_RUBY_SWIRL".to_string(),
            "ALCREMIE_CARAMEL_SWIRL".to_string(),
            "ALCREMIE_RAINBOW_SWIRL".to_string(),
            "ALCREMIE_STRAWBERRY_RUBY_CREAM".to_string(),
            "ALCREMIE_STRAWBERRY_MATCHA_CREAM".to_string(),
            "ALCREMIE_STRAWBERRY_MINT_CREAM".to_string(),
            "ALCREMIE_STRAWBERRY_LEMON_CREAM".to_string(),
            "ALCREMIE_STRAWBERRY_SALTED_CREAM".to_string(),
            "ALCREMIE_STRAWBERRY_RUBY_SWIRL".to_string(),
            "ALCREMIE_STRAWBERRY_CARAMEL_SWIRL".to_string(),
            "ALCREMIE_STRAWBERRY_RAINBOW_SWIRL".to_string()
        ]),
        Pokemon::Zarude => get_random_name_from_list_with_prefered(settings,vec![
            "ZARUDE".to_string(),
            "ZARUDE_DADA".to_string()
        ],0),
        Pokemon::Ursaluna => get_random_name_from_list_with_prefered(settings,vec![
            "URSALUNA".to_string(),
            "URSALUNA_BLOODMOON".to_string()
        ],0),
        Pokemon::Maushold => get_random_name_from_list(settings,vec![
            "MAUSHOLD_FAMILY_OF_THREE".to_string(),
            "MAUSHOLD_FAMILY_OF_FOUR".to_string()
        ]),
        Pokemon::Squawkabilly => get_random_name_from_list(settings,vec![
            "SQUAWKABILLY_GREEN_PLUMAGE".to_string(),
            "SQUAWKABILLY_BLUE_PLUMAGE".to_string(),
            "SQUAWKABILLY_YELLOW_PLUMAGE".to_string(),
            "SQUAWKABILLY_WHITE_PLUMAGE".to_string()
        ]),
        Pokemon::Tatsugiri => get_random_name_from_list(settings,vec![
            "TATSUGIRI_CURLY".to_string(),
            "TATSUGIRI_DROOPY".to_string(),
            "TATSUGIRI_STRETCHY".to_string()
        ]),
        Pokemon::Dudunsparce => get_random_name_from_list(settings,vec![
            "DUDUNSPARCE_TWO_SEGMENT".to_string(),
            "DUDUNSPARCE_THREE_SEGMENT".to_string()
        ]),
        Pokemon::Gimmighoul => get_random_name_from_list(settings,vec![
            "GIMMIGHOUL_CHEST".to_string(),
            "GIMMIGHOUL_ROAMING".to_string()
        ]),
        Pokemon::Poltchageist => get_random_name_from_list(settings,vec![
            "POLTCHAGEIST_COUNTERFEIT".to_string(),
            "POLTCHAGEIST_ARTISAN".to_string()
        ]),
        Pokemon::Sinistcha => get_random_name_from_list(settings,vec![
            "SINISTCHA_UNREMARKABLE".to_string(),
            "SINISTCHA_MASTERPIECE".to_string()
        ]),
        _ => "".to_string()
    };
}

fn get_random_name_from_list(settings: &mut settings::Settings,list_of_names: Vec<String>) -> String{
    let index = settings::get_next_seed(0,list_of_names.len() as i32 -1,settings);
    return list_of_names[index as usize].clone();
}
fn get_random_name_from_list_with_prefered(settings: &mut settings::Settings,list_of_names: Vec<String>,prefered_index: i16) -> String{
    if settings::get_next_seed(0,1,settings) == 1{
        return list_of_names[prefered_index as usize].clone();
    }
    return get_random_name_from_list(settings,list_of_names);
}
