use std::process::Command;

use crate::src::gen3::evolution_changes::setup_evolution_fixes;
use crate::src::gen3::item_randomization;
use crate::src::pokemon::read_all_pokemon;
use crate::src::settings;
use crate::src::gen3::wild_pokemon;
use crate::src::gen3::trainers;
use crate::src::gen3::starter_randomization;
use crate::src::gen3::create_rando_script;
use crate::src::hint_system;
use crate::src::game_chooser;
use std::env;
//File that contains the functions that will be called by the launcher

//Randomizes every pokemon in the game according to json file
//filename should point to a Json file generated by the launcher with all the settings & Seed
pub fn randomize_pokemon(settings : &mut settings::Settings){
    //let mut settings = create_sample_settings();
    println!("Starting Rom Randomization Process");
    let pkmn_data = read_all_pokemon(settings);
    wild_pokemon::randomize_wild_pokemon(settings,&pkmn_data);
    let starters = game_chooser::do_starter_randomization(settings, &pkmn_data);
    let gym_types = game_chooser::do_trainer_randomization(settings,&pkmn_data,starters);
    setup_evolution_fixes(settings);

    let mut all_items : Vec<item_randomization::Item> = item_randomization::randomize_items(settings,&pkmn_data,&gym_types);

    create_rando_script::create_rando_scripts(settings,all_items);

    //Keep the professor pokemon at the end so people can use it to make sure they have the same seed as a friend
    game_chooser::randomize_professor_pokemon(settings, &pkmn_data);
    hint_system::create_spoiler_log(settings);
    //If in Testing Mode, don't create the full rom
    if settings.testing_mode{
        return;
    }
    build_rom(settings);
}

pub fn build_rom(settings : &mut settings::Settings){
    let make_rom_path = game_chooser::build_rom(settings);
    let path = env::current_dir().unwrap();
    Command::new("sh")
    .arg("-C")
    .arg(format!("{}/{}",path.display(),make_rom_path))
    .arg(settings.seed.clone())
    .spawn()
    .expect("sh command failed to start");
}