use crate::pokemon::{LIST_OF_POKEMON, LegendStatus};
use crate::settings;
use crate::pokemon;
use json;
use std::fs;
//File that contains the functions that will be called by the launcher

//Randomizes every pokemon in the game according to json file
//filename should point to a Json file generated by the launcher with all the settings & Seed
pub fn randomize_pokemon(settings: &mut settings::Settings){
    if settings.randomize_wild_pokemon{
        randomize_wild_pokemon(settings);
    }
}

const NUMBER_OF_ROUTES: usize = 124;
fn randomize_wild_pokemon(settings: &mut settings::Settings){
    let data = fs::read_to_string("decomp/pokeemerald-expansion/src/data/wild_encounters.json").expect("unable to read file");
    let mut parsed_data = json::parse(&data).unwrap();
    for i in 0..NUMBER_OF_ROUTES{
        println!("{}", i);
        for place in ["land_mons","water_mons","fishing_mons"]{
            for j in 0..30{ //Land Mons
                if parsed_data["wild_encounter_groups"][0]["encounters"]
                [i][place]["mons"][j]["species"] == json::JsonValue::Null{
                    break;
                }
                parsed_data["wild_encounter_groups"][0]["encounters"]
                [i][place]["mons"][j]["species"] = get_random_wild_pokemon(settings).into();
            }
        }
    }
    //write to file
    fs::write("decomp/pokeemerald-expansion/src/data/wild_encounters.json",
    parsed_data.to_string()).expect("couldn't write to file");
}

//Gets a pokemon, checks if it can be put there, and returns the value
fn get_random_wild_pokemon(settings: &mut settings::Settings) -> String{
    //Make Random Pokemon
    let rand_val = settings::get_next_seed(0, LIST_OF_POKEMON.len() as i32, settings);
    let pokemon = &LIST_OF_POKEMON[rand_val as usize];
    //Check if it is a valid pokemon
    if !settings.allow_pokemon_past_generation && pokemon.generation > 3{
        return get_random_wild_pokemon(settings);
    }
    if !settings.allow_legends_in_wild_pool && pokemon.status == LegendStatus::Legendary{
        return get_random_wild_pokemon(settings);
    }
    if !settings.allow_megas_in_wild_pool && pokemon.status == LegendStatus::Mega{
        return get_random_wild_pokemon(settings);
    }

    //Return if it passes all checks
    return pokemon::convert_name(pokemon);
}

pub fn build_rom(){

}