use crate::pokemon::read_all_pokemon;
use crate::settings;
use crate::gen3::wild_pokemon;
use crate::gen3::trainers;
//File that contains the functions that will be called by the launcher

//Randomizes every pokemon in the game according to json file
//filename should point to a Json file generated by the launcher with all the settings & Seed
pub fn randomize_pokemon(settings: &mut settings::Settings){
    let pkmn_data = read_all_pokemon();
    wild_pokemon::randomize_wild_pokemon(settings,&pkmn_data);
    trainers::shuffle_trainers(settings,&pkmn_data);
}

pub fn build_rom(){

}