use crate::pokemon::{LIST_OF_POKEMON, LegendStatus};
use crate::settings;
use crate::gen3::wild_pokemon;
use crate::gen3::trainers;
use crate::pokemon;
use json;
use std::fs;
//File that contains the functions that will be called by the launcher

//Randomizes every pokemon in the game according to json file
//filename should point to a Json file generated by the launcher with all the settings & Seed
pub fn randomize_pokemon(settings: &mut settings::Settings){
    wild_pokemon::randomize_wild_pokemon(settings);
    trainers::shuffle_trainers(settings);
}

pub fn build_rom(){

}